name: Solanaizer AI Audit

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v4
      - name: Solanaizer Audit
        continue-on-error: false
        uses: solanaizer/solanaizer-action