name: Soteria Audit

# Triggers the workflow on push or pull request to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Check-out the repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js 20 (you can adjust this if needed)
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Run Soteria Audit
      - name: Soteria Audit
        continue-on-error: false  # Set to true if you want the job to continue despite errors
        uses: silas-x/soteria-action@main